[app]
name = "Tuleaj Plugin Aggregator"
version = "1.0.0"
description = "PySide6 QML 插件聚合工具"
author = "Tuleaj"

[ui]
theme = "auto"

[environments]
default = "python3.11"
available = [ "python3.11", "python3.12",]
current = "test"
current_path = "C:\\Users\\tulea\\Desktop\\tmp\\code\\tuleaj-plugin-aggregator\\envs\\test"
current_python_version = "Python 3.11.13"
[[environments.scanned_environments]]
created_time = 1759726185.017113
is_active = true
name = "test"
packages_count = 6
path = "C:\\Users\\tulea\\Desktop\\tmp\\code\\tuleaj-plugin-aggregator\\envs\\test"
python_version = "Python 3.11.13"
size_mb = 609.34

[[environments.scanned_environments]]
created_time = 1759739053.8794825
is_active = false
name = "test2"
packages_count = 0
path = "C:\\Users\\tulea\\Desktop\\tmp\\code\\tuleaj-plugin-aggregator\\envs\\test2"
python_version = "Python 3.11.13"
size_mb = 0.52

[plugins]
directory = "plugins"
auto_scan = true
plugin_timeout_seconds = 30
installed_plugins = []

[mirrors]
enabled = true
default_source = "pypi"
timeout_seconds = 30
retry_count = 3
verify_ssl = true
[[mirrors.sources]]
name = "pypi"
url = "https://pypi.org/simple/"
priority = 1
enabled = false

[[mirrors.sources]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = 2
enabled = true

[[mirrors.sources]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = 3
enabled = true

[logging]
enable_file_logging = true
enable_console_logging = true
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
date_format = "%Y-%m-%d %H:%M:%S"
enable_plugin_logs = true
plugin_log_dir = "logs/plugins"
log_level = "INFO"
log_dir = "logs"
max_log_files = 10
log_file_size_mb = 10

[advanced]
debug_mode = false
enable_metrics = true
metrics_retention_days = 30
enable_telemetry = false

[dependencies]
lazy_loading_enabled = true
install_timeout_seconds = 300
show_install_progress = true
version_resolution_strategy = "strict"
auto_cleanup_unused = false
